export const ADD_ONE_BILL = 'ADD_BILL';
export const ADD_MANY_BILL = 'ADD_MANY_BILL';
export const UPDATE_ONE_BILL = 'UPDATE_ONE_BILL';
export const UPDATE_MANY_BILL = 'UPDATE_MANY_BILL';
export const REMOVE_ONE_BILL = 'REMOVE_ONE_BILL';
export const REMOVE_MANY_BILL = 'REMOVE_MANY_BILL';
export const RESET_BILL = 'RESET_BILL';

export const ADD_ONE_EXPENSE = 'ADD_EXPENSE';
export const ADD_MANY_EXPENSE = 'ADD_MANY_EXPENSE';
export const UPDATE_ONE_EXPENSE = 'UPDATE_ONE_EXPENSE';
export const UPDATE_MANY_EXPENSE = 'UPDATE_MANY_EXPENSE';
export const REMOVE_ONE_EXPENSE = 'REMOVE_ONE_EXPENSE';
export const REMOVE_MANY_EXPENSE = 'REMOVE_MANY_EXPENSE';
export const RESET_EXPENSE = 'RESET_EXPENSE';

export const ADD_ONE_ITEM = 'ADD_ITEM';
export const ADD_MANY_ITEM = 'ADD_MANY_ITEM';
export const UPDATE_ONE_ITEM = 'UPDATE_ONE_ITEM';
export const UPDATE_MANY_ITEM = 'UPDATE_MANY_ITEM';
export const REMOVE_ONE_ITEM = 'REMOVE_ONE_ITEM';
export const REMOVE_MANY_ITEM = 'REMOVE_MANY_ITEM';
export const RESET_ITEM = 'RESET_ITEM';

export const ADD_ONE_USER = 'ADD_USER';
export const ADD_MANY_USER = 'ADD_MANY_USER';
export const UPDATE_ONE_USER = 'UPDATE_ONE_USER';
export const UPDATE_MANY_USER = 'UPDATE_MANY_USER';
export const REMOVE_ONE_USER = 'REMOVE_ONE_USER';
export const REMOVE_MANY_USER = 'REMOVE_MANY_USER';
export const RESET_USER = 'RESET_USER';
